apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keresifon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kere-sifon/keresifon.git
    targetRevision: main
    # ArgoCD auto-detects the kustomization.yaml in this path.
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: keresifon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
